/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015-2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include <migraphx/instruction.hpp>
#include <migraphx/literal.hpp>
#include <migraphx/make_op.hpp>
#include <migraphx/program.hpp>
#include <migraphx/register_target.hpp>
#include <migraphx/verify.hpp>

#include <test.hpp>

static std::vector<float> run_gpu_topk_values(migraphx::program p,
                                              const migraphx::parameter_map& host_params)
{
    migraphx::target t = migraphx::make_target("gpu");
    p.compile(t);

    migraphx::parameter_map gpu_params;
    for(auto&& x : p.get_parameter_shapes())
    {
        auto it = host_params.find(x.first);
        if(it != host_params.end())
            gpu_params[x.first] = t.copy_to(it->second);
        else
            gpu_params[x.first] = t.allocate(x.second);
    }

    auto results = p.eval(gpu_params);
    auto host    = t.copy_from(results.at(0));

    std::vector<float> values;
    host.visit([&](auto v) { values.assign(v.begin(), v.end()); });
    return values;
}

// Builds the SSD-style nonmaxsuppression -> gather(scores) -> topk chain that
// simplify_dyn_ops::find_nms_gather_topk rewrites. NMS output is static [max_boxes, 3] with only
// num_selected valid rows; the padded rows point at box 0, so the gather pulls box 0's (highest)
// score into every padded slot. Without the where-mask rewrite the topk returns duplicates of
// box 0's score instead of the real detections. Data/gold are generated by
// test/gpu/gen_ssd_rewrite_data.py using onnxruntime.
TEST_CASE(test_ssd_rewrite)
{
    migraphx::program p;
    auto* mm = p.get_main_module();
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 4, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 4}};

    auto boxes     = mm->add_parameter("boxes", boxes_s);
    auto scores    = mm->add_parameter("scores", scores_s);
    auto max_out_l = mm->add_literal(int64_t{4});
    auto iou_l     = mm->add_literal(0.5f);
    auto score_l   = mm->add_literal(0.0f);

    auto nms = mm->add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes, scores, max_out_l, iou_l, score_l);
    auto indices = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms);
    // box-index column (column 2) of the [max_boxes, 3] selected indices
    auto box_col = mm->add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), indices);
    auto box_col_1d  = mm->add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col);
    auto scores_flat = mm->add_instruction(migraphx::make_op("reshape", {{"dims", {4}}}), scores);
    auto gathered =
        mm->add_instruction(migraphx::make_op("gather", {{"axis", 0}}), scores_flat, box_col_1d);
    auto topk = mm->add_instruction(
        migraphx::make_op("topk", {{"k", 3}, {"axis", 0}, {"largest", 1}}), gathered);
    auto vals = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), topk);
    mm->add_return({vals});

    // Corner format [y1, x1, y2, x2]; box 3 duplicates box 2 so NMS suppresses it, leaving
    // num_selected = 3 (< max_boxes = 4) and one zero-padded row that resolves to box 0.
    std::vector<float> boxes_vec  = {0.0f,
                                     0.0f,
                                     1.0f,
                                     1.0f,
                                     0.0f,
                                     2.0f,
                                     1.0f,
                                     3.0f,
                                     0.0f,
                                     4.0f,
                                     1.0f,
                                     5.0f,
                                     0.0f,
                                     4.0f,
                                     1.0f,
                                     5.0f};
    std::vector<float> scores_vec = {0.9f, 0.8f, 0.7f, 0.6f};

    migraphx::parameter_map host_params;
    host_params["boxes"]  = migraphx::argument(boxes_s, boxes_vec.data());
    host_params["scores"] = migraphx::argument(scores_s, scores_vec.data());

    auto values = run_gpu_topk_values(std::move(p), host_params);

    // Top-3 scores of the selected boxes (0, 1, 2); box 0's score must appear once, not once per
    // padded row.
    std::vector<float> gold = {0.9f, 0.8f, 0.7f};
    EXPECT(migraphx::verify::verify_rms_range(values, gold));
}

int main(int argc, const char* argv[]) { test::run(argc, argv); }
