/*
 * The MIT License (MIT)
 *
 * Copyright (c) 2015-2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include <migraphx/instruction.hpp>
#include <migraphx/literal.hpp>
#include <migraphx/make_op.hpp>
#include <migraphx/program.hpp>
#include <migraphx/register_target.hpp>
#include <migraphx/verify.hpp>
#include <migraphx/gpu/rewrite_ssd.hpp>
#include <migraphx/dead_code_elimination.hpp>
#include <migraphx/pass_manager.hpp>

#include <test.hpp>
#include <limits>

static std::vector<float> run_gpu_topk_values(migraphx::program p,
                                              const migraphx::parameter_map& host_params)
{
    migraphx::target t = migraphx::make_target("gpu");
    p.compile(t);

    migraphx::parameter_map gpu_params;
    for(auto&& x : p.get_parameter_shapes())
    {
        auto it = host_params.find(x.first);
        if(it != host_params.end())
            gpu_params[x.first] = t.copy_to(it->second);
        else
            gpu_params[x.first] = t.allocate(x.second);
    }

    auto results = p.eval(gpu_params);
    auto host    = t.copy_from(results.at(0));

    std::vector<float> values;
    host.visit([&](auto v) { values.assign(v.begin(), v.end()); });
    return values;
}

// Builds the SSD-style nonmaxsuppression -> gather(scores) -> topk chain that gpu::rewrite_ssd
// rewrites. NMS output is static [max_boxes, 3] with only
// num_selected valid rows. The padded rows point at box 0, so the gather pulls box 0's (highest)
// score into every padded slot. Without the where-mask rewrite the topk returns duplicates of
// box 0's score instead of the real detections. Data/gold were generated by using onnxruntime.
TEST_CASE(test_ssd_rewrite)
{
    migraphx::program p;
    auto* mm = p.get_main_module();
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 4, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 4}};

    auto boxes     = mm->add_parameter("boxes", boxes_s);
    auto scores    = mm->add_parameter("scores", scores_s);
    auto max_out_l = mm->add_literal(int64_t{4});
    auto iou_l     = mm->add_literal(0.5f);
    auto score_l   = mm->add_literal(0.0f);

    auto nms = mm->add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes, scores, max_out_l, iou_l, score_l);
    auto indices = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms);
    auto num_selected =
        mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), nms);
    // variable-end slice trimming the padded indices to num_selected, exactly as the ONNX NMS
    // parser emits; find_nms_gather_topk rewrites this into a static, mask-based form.
    auto selected = mm->add_instruction(
        migraphx::make_op("slice", {{"axes", {0}}, {"starts", {0}}}), indices, num_selected);
    // box-index column (column 2) of the [num_selected, 3] selected indices
    auto box_col = mm->add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), selected);
    auto box_col_1d = mm->add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col);
    // flatten the static score table to 1D (gather data); box_col_1d holds the indices
    auto scores_flat =
        mm->add_instruction(migraphx::make_op("squeeze", {{"axes", {0, 1}}}), scores);
    auto gathered =
        mm->add_instruction(migraphx::make_op("gather", {{"axis", 0}}), scores_flat, box_col_1d);
    auto topk = mm->add_instruction(
        migraphx::make_op("topk", {{"k", 3}, {"axis", 0}, {"largest", 1}}), gathered);
    auto vals = mm->add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), topk);
    mm->add_return({vals});

    // Corner format [y1, x1, y2, x2]; box 3 duplicates box 2 so NMS suppresses it, leaving
    // num_selected = 3 (< max_boxes = 4) and one zero-padded row that resolves to box 0.
    std::vector<float> boxes_vec  = {0.0f,
                                     0.0f,
                                     1.0f,
                                     1.0f,
                                     0.0f,
                                     2.0f,
                                     1.0f,
                                     3.0f,
                                     0.0f,
                                     4.0f,
                                     1.0f,
                                     5.0f,
                                     0.0f,
                                     4.0f,
                                     1.0f,
                                     5.0f};
    std::vector<float> scores_vec = {0.9f, 0.8f, 0.7f, 0.6f};

    migraphx::parameter_map host_params;
    host_params["boxes"]  = migraphx::argument(boxes_s, boxes_vec.data());
    host_params["scores"] = migraphx::argument(scores_s, scores_vec.data());

    auto values = run_gpu_topk_values(std::move(p), host_params);

    // Top-3 scores of the selected boxes (0, 1, 2); box 0's score must appear once, not once per
    // padded row.
    std::vector<float> gold = {0.9f, 0.8f, 0.7f};
    EXPECT(migraphx::verify::verify_rms_range(values, gold));
}

static void run_pass(migraphx::module& m)
{
    migraphx::run_passes(m, {migraphx::gpu::rewrite_ssd{}, migraphx::dead_code_elimination{}});
}

// Build boxes/scores -> nonmaxsuppression -> dynamic slice -> gather scores -> topk in `m`
// (matching what the ONNX NMS parser emits), returning the gather so callers can extend the graph.
static migraphx::instruction_ref make_nms_gather_topk(migraphx::module& m, bool largest)
{
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 4, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 4}};
    auto boxes     = m.add_parameter("boxes", boxes_s);
    auto scores    = m.add_parameter("scores", scores_s);
    auto max_out   = m.add_literal(int64_t{4});
    auto iou       = m.add_literal(0.5f);
    auto score_thr = m.add_literal(0.0f);
    auto nms       = m.add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes, scores, max_out, iou, score_thr);
    auto indices      = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms);
    auto num_selected = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), nms);
    auto selected     = m.add_instruction(
        migraphx::make_op("slice", {{"axes", {0}}, {"starts", {0}}}), indices, num_selected);
    auto box_col = m.add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), selected);
    auto box_col_1d  = m.add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col);
    auto scores_flat = m.add_instruction(migraphx::make_op("squeeze", {{"axes", {0, 1}}}), scores);
    auto gather =
        m.add_instruction(migraphx::make_op("gather", {{"axis", 0}}), scores_flat, box_col_1d);
    auto topk = m.add_instruction(
        migraphx::make_op("topk", {{"k", 4}, {"axis", 0}, {"largest", largest ? 1 : 0}}), gather);
    auto tv = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), topk);
    m.add_return({tv});
    return gather;
}

// The graph gpu::rewrite_ssd is expected to produce for make_nms_gather_topk: the dynamic slice is
// gone and the gathered scores are masked so the padded rows become a sentinel. Insertion order
// mirrors the pass so the printed IR (compared by module equality) matches.
static void make_nms_gather_topk_masked(migraphx::module& m, bool largest)
{
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 4, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 4}};
    auto boxes     = m.add_parameter("boxes", boxes_s);
    auto scores    = m.add_parameter("scores", scores_s);
    auto max_out   = m.add_literal(int64_t{4});
    auto iou       = m.add_literal(0.5f);
    auto score_thr = m.add_literal(0.0f);
    auto iota_lit  = m.add_literal(
        migraphx::literal{migraphx::shape{migraphx::shape::int64_type, {4}}, {0, 1, 2, 3}});
    auto sentinel_val =
        largest ? std::numeric_limits<float>::lowest() : std::numeric_limits<float>::max();
    auto sentinel = m.add_literal(
        migraphx::literal{migraphx::shape{migraphx::shape::float_type, {1}}, {sentinel_val}});
    auto nms = m.add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes, scores, max_out, iou, score_thr);
    auto indices      = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms);
    auto num_selected = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), nms);
    auto box_col      = m.add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), indices);
    auto box_col_1d  = m.add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col);
    auto scores_flat = m.add_instruction(migraphx::make_op("squeeze", {{"axes", {0, 1}}}), scores);
    auto gather =
        m.add_instruction(migraphx::make_op("gather", {{"axis", 0}}), scores_flat, box_col_1d);
    auto num_selected_bc =
        m.add_instruction(migraphx::make_op("multibroadcast", {{"out_lens", {4}}}), num_selected);
    auto less = m.add_instruction(migraphx::make_op("less"), iota_lit, num_selected_bc);
    auto mask = m.add_instruction(
        migraphx::make_op("convert", {{"target_type", migraphx::shape::bool_type}}), less);
    auto sentinel_bc =
        m.add_instruction(migraphx::make_op("multibroadcast", {{"out_lens", {4}}}), sentinel);
    auto masked = m.add_instruction(migraphx::make_op("where"), mask, gather, sentinel_bc);
    auto topk   = m.add_instruction(
        migraphx::make_op("topk", {{"k", 4}, {"axis", 0}, {"largest", largest ? 1 : 0}}), masked);
    auto tv = m.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), topk);
    m.add_return({tv});
}

TEST_CASE(nms_gather_topk_largest)
{
    migraphx::module m1;
    make_nms_gather_topk(m1, true);
    run_pass(m1);

    migraphx::module m2;
    make_nms_gather_topk_masked(m2, true);

    EXPECT(m1 == m2);
}

TEST_CASE(nms_gather_topk_smallest)
{
    migraphx::module m1;
    make_nms_gather_topk(m1, false);
    run_pass(m1);

    migraphx::module m2;
    make_nms_gather_topk_masked(m2, false);

    EXPECT(m1 == m2);
}

// A second dynamic NMS slice in the ancestor cone makes it ambiguous, so the rewrite must not fire.
TEST_CASE(nms_gather_topk_two_nms_no_change)
{
    migraphx::module m1;
    auto gather = make_nms_gather_topk(m1, true);
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 4, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 4}};
    auto boxes2  = m1.add_parameter("boxes2", boxes_s);
    auto scores2 = m1.add_parameter("scores2", scores_s);
    auto nms2    = m1.add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes2, scores2, m1.add_literal(int64_t{4}));
    auto indices2 = m1.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms2);
    auto num_selected2 =
        m1.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), nms2);
    auto selected2 = m1.add_instruction(
        migraphx::make_op("slice", {{"axes", {0}}, {"starts", {0}}}), indices2, num_selected2);
    auto box_col2 = m1.add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), selected2);
    auto box_col2_1d = m1.add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col2);
    // Mask R-CNN concatenates the selected box indices from multiple NMS ops before the final
    // gather/topk; two NMS slices in the ancestor cone must leave the pass a no-op.
    auto gather_idx   = gather->inputs().at(1);
    auto concatenated = m1.insert_instruction(
        gather, migraphx::make_op("concat", {{"axis", 0}}), gather_idx, box_col2_1d);
    m1.replace_instruction(gather, gather->get_operator(), gather->inputs().at(0), concatenated);

    migraphx::module m2 = m1;
    run_pass(m1);

    EXPECT(m1 == m2);
}

// Full SSD output tail: parse_topk's var-k slices feed downstream gathers. rewrite_ssd should set
// the topk k to the cap (min-with-dim literal = 3), keep the gathers static, and trim only the
// output to min(cap, num_selected). Distinct dims (max_boxes=5, coords=4, cap=3) keep the output
// detection axis unambiguous.
TEST_CASE(nms_gather_topk_static_outputs)
{
    migraphx::module m1;
    migraphx::shape boxes_s{migraphx::shape::float_type, {1, 5, 4}};
    migraphx::shape scores_s{migraphx::shape::float_type, {1, 1, 5}};
    auto boxes     = m1.add_parameter("boxes", boxes_s);
    auto scores    = m1.add_parameter("scores", scores_s);
    auto max_out   = m1.add_literal(int64_t{5});
    auto iou       = m1.add_literal(0.5f);
    auto score_thr = m1.add_literal(0.0f);
    auto nms       = m1.add_instruction(
        migraphx::make_op("nonmaxsuppression"), boxes, scores, max_out, iou, score_thr);
    auto indices = m1.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 0}}), nms);
    auto num_selected =
        m1.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), nms);
    auto selected = m1.add_instruction(
        migraphx::make_op("slice", {{"axes", {0}}, {"starts", {0}}}), indices, num_selected);
    auto box_col = m1.add_instruction(
        migraphx::make_op("slice", {{"axes", {1}}, {"starts", {2}}, {"ends", {3}}}), selected);
    auto box_col_1d  = m1.add_instruction(migraphx::make_op("squeeze", {{"axes", {1}}}), box_col);
    auto scores_flat = m1.add_instruction(migraphx::make_op("squeeze", {{"axes", {0, 1}}}), scores);
    auto gathered =
        m1.add_instruction(migraphx::make_op("gather", {{"axis", 0}}), scores_flat, box_col_1d);
    auto topk = m1.add_instruction(
        migraphx::make_op("topk", {{"k", 5}, {"axis", 0}, {"largest", 1}}), gathered);
    auto topk_ind = m1.add_instruction(migraphx::make_op("get_tuple_elem", {{"index", 1}}), topk);
    // parse_topk var-k: k = min(cap=3, dim = elements of gathered scores)
    auto dim = m1.add_instruction(migraphx::make_op("dimensions_of", {{"start", 0}, {"end", 1}}),
                                  gathered);
    auto cap_lit =
        m1.add_literal(migraphx::literal{migraphx::shape{migraphx::shape::int64_type, {1}}, {3}});
    auto kcat       = m1.add_instruction(migraphx::make_op("concat", {{"axis", 0}}), cap_lit, dim);
    auto k          = m1.add_instruction(migraphx::make_op("reduce_min", {{"axes", {0}}}), kcat);
    auto sliced_ind = m1.add_instruction(
        migraphx::make_op("slice", {{"axes", {0}}, {"starts", {0}}}), topk_ind, k);
    // downstream: gather the box coordinates and add a batch dim
    auto boxes_table = m1.add_instruction(migraphx::make_op("squeeze", {{"axes", {0}}}), boxes);
    auto det_boxes =
        m1.add_instruction(migraphx::make_op("gather", {{"axis", 0}}), boxes_table, sliced_ind);
    auto out = m1.add_instruction(migraphx::make_op("unsqueeze", {{"axes", {0}}}), det_boxes);
    m1.add_return({out});

    run_pass(m1);

    // Only the output is dynamic: it is a slice trimming to min(cap, num_selected).
    auto ret = std::prev(m1.end());
    EXPECT(ret->name() == "@return");
    auto out_slice = ret->inputs().at(0);
    EXPECT(out_slice->name() == "slice");
    EXPECT(out_slice->get_shape().dynamic());

    auto new_k = out_slice->inputs().at(1);
    EXPECT(new_k->name() == "min");
    EXPECT(new_k->inputs().at(0)->name() == "@literal"); // cap
    auto num_sel = new_k->inputs().at(1);                // num_selected from the NMS
    EXPECT(num_sel->name() == "get_tuple_elem");
    EXPECT(num_sel->inputs().at(0)->name() == "nonmaxsuppression");

    // Everything feeding the trim is static (static until the outputs).
    auto unsq = out_slice->inputs().at(0);
    EXPECT(not unsq->get_shape().dynamic());

    // The TopK now sorts only cap = 3 (the maximum k), on a static input.
    auto det_gather = unsq->inputs().at(0);
    auto topk_gte   = det_gather->inputs().at(1);
    auto topk_new   = topk_gte->inputs().at(0);
    EXPECT(topk_new->name() == "topk");
    EXPECT(topk_new->get_operator().to_value().at("k").to<int>() == 3);
    EXPECT(not topk_new->inputs().at(0)->get_shape().dynamic());
}

int main(int argc, const char* argv[]) { test::run(argc, argv); }
