
#ifndef MIGRAPH_GUARD_PASS_CONFIG_HPP
#define MIGRAPH_GUARD_PASS_CONFIG_HPP

#include <migraph/env.hpp>

namespace migraph {
MIGRAPH_DECLARE_ENV_VAR(MIGRAPH_DISABLE_MEMORY_COLORING)
MIGRAPH_DECLARE_ENV_VAR(MIGRAPH_UNIFY_MEMORY_COLORING)

} // namespace migraph
#endif // MIGRAPH_GUARD_PASS_CONFIG_HPP
