variables:
- group: common
- template: /.azuredevops/variables-global.yml@pipelines_repo

parameters:
- name: pipelinesRepoRef
  type: string
  default: refs/heads/develop

resources:
  repositories:
  - repository: pipelines_repo
    type: github
    endpoint: ROCm
    name: ROCm/ROCm
    ref: ${{ parameters.pipelinesRepoRef }}

trigger:
  batch: true
  branches:
    include:
    - develop
    - master
  paths:
    exclude:
    - .githooks
    - .github
    - docs
    - '.*.y*ml'
    - '*.md'
    - Jenkinsfile
    - LICENSE

pr:
  autoCancel: true
  branches:
    include:
    - develop
    - master
  paths:
    exclude:
    - .github
    - docs
    - '.*.y*ml'
    - '*.md'
    - Jenkinsfile
    - LICENSE
  drafts: false

jobs:
  - template: ${{ variables.CI_COMPONENT_PATH }}/AMDMIGraphX.yml@pipelines_repo
