#####################################################################################
# The MIT License (MIT)
#
# Copyright (c) 2015-2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
#####################################################################################

include_guard()

function(__get_target_link_libraries target output)
    if(TARGET ${target})
        set(__options "")
        set(__one_value_args FILTER)
        set(__multi_value_args "")
        cmake_parse_arguments(arg "${__options}" "${__one_value_args}" "${__multi_value_args}" ${ARGN})
        get_target_property(__imported ${target} IMPORTED)
        set(__property LINKED_LIBRARIES)
        if(__imported)
            set(__property INTERFACE_LINK_LIBRARIES)
        endif()
        get_target_property(__raw_libraries ${target} ${__property})
        if(arg_FILTER)
            list(FILTER __raw_libraries INCLUDE REGEX ${arg_FILTER})
        endif()
        set(${output} "${__raw_libraries}" PARENT_SCOPE)
    endif()
endfunction()

function(__set_target_link_libraries target libraries)
    if(TARGET ${target})
        get_target_property(__imported ${target} IMPORTED)
        set(__property LINKED_LIBRARIES)
        if(__imported)
            set(__property INTERFACE_LINK_LIBRARIES)
        endif()
        set_target_properties(${target} PROPERTIES ${__property} "${libraries}")
    endif()
endfunction()

function(__impl_get_target_linked_libraries target output visited)
    list(FIND ${visited} ${target} __visited)
    if(__visited EQUAL -1)
        list(APPEND ${visited} ${target})
        set(__options FLATTEN)
        set(__one_value_args FILTER)
        set(__multi_value_args "")
        cmake_parse_arguments(arg "${__options}" "${__one_value_args}" "${__multi_value_args}" ${ARGN})
        if(arg_FILTER)
            set(__filter FILTER ${arg_FILTER})
        endif()
        __get_target_link_libraries(${target} __libraries ${__filter})
        if(arg_FLATTEN)
            foreach(__target ${__libraries})
                __impl_get_target_linked_libraries(${__target} __target_libraries "${visited}" FLATTEN "${__filter}")
                list(APPEND __flatten_libraries ${__target_libraries})
            endforeach()
            list(APPEND __libraries ${__flatten_libraries})
        endif()
        list(REMOVE_DUPLICATES __libraries)
    endif()
    set(${output} "${__libraries}" PARENT_SCOPE)
    set(${visited} "${${visited}}" PARENT_SCOPE)
endfunction()

function(get_target_linked_libraries target output)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "${target}: required a CMake target")
    endif()
    set(__options FLATTEN)
    set(__one_value_args FILTER)
    set(__multi_value_args "")
    cmake_parse_arguments(arg "${__options}" "${__one_value_args}" "${__multi_value_args}" ${ARGN})
    if (arg_FLATTEN)
        set(__flatten FLATTEN)
    endif()
    if (arg_FILTER)
        set(__filter FILTER ${arg_FILTER})
    endif()
    __impl_get_target_linked_libraries(${target} __libraries __targets_visited ${__flatten} ${__filter})
    list(REMOVE_DUPLICATES __libraries)
    set(${output} ${__libraries} PARENT_SCOPE)
endfunction()

function(remove_target_linked_libraries target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "${target}: required a CMake target or imported target")
    endif()
    set(__options FLATTEN)
    set(__one_value_args FILTER LIBRARIES)
    set(__multi_value_args "")
    cmake_parse_arguments(arg "${__options}" "${__one_value_args}" "${__multi_value_args}" ${ARGN})
    if(NOT arg_LIBRARIES OR arg_LIBRARIES STREQUAL "")
        return()
    endif()
    if(arg_FILTER)
        set(__filter FILTER ${arg_FILTER})
    endif()
    if(arg_FLATTEN)
        set(__flatten FLATTEN)
    endif()
    __impl_get_target_linked_libraries(${target} __libraries __targets_visited ${__flatten} ${__filter})
    list(REMOVE_DUPLICATES __libraries)
    foreach(__library ${target} ${__libraries})
        if(TARGET ${__library})
            __get_target_link_libraries(${__library} __target_libraries)
            list(REMOVE_ITEM __target_libraries ${arg_LIBRARIES})
            __set_target_link_libraries(${__library} "${__target_libraries}")
        endif()
    endforeach()
endfunction()

function(filter_target_linked_libraries target)
    if(NOT TARGET ${target})
        message(FATAL_ERROR "${target}: required a CMake target or imported target")
    endif()
    set(__options FLATTEN INCLUDE EXCLUDE)
    set(__one_value_args FILTER REGEX)
    set(__multi_value_args "")
    cmake_parse_arguments(arg "${__options}" "${__one_value_args}" "${__multi_value_args}" ${ARGN})
    if(NOT arg_REGEX OR arg_REGEX STREQUAL "")
        return()
    endif()
    set(__operation EXCLUDE)
    if(arg_INCLUDE AND arg_EXCLUDE)
        message(WARNING "INCLUDE and EXCLUDE are mutually exclusive, defaulting to EXCLUDE")
    elseif(arg_INCLUDE)
        set(__operation INCLUDE)
    endif()
    if(arg_FILTER)
        set(__filter FILTER ${arg_FILTER})
    endif()
    if(arg_FLATTEN)
        set(__flatten FLATTEN)
    endif()
    __impl_get_target_linked_libraries(${target} __libraries __targets_visited ${__flatten} ${__filter})
    list(REMOVE_DUPLICATES __libraries)
    foreach(__library ${__libraries})
        __get_target_link_libraries(${__library} __target_libraries)
        list(FILTER __target_libraries ${__operation} REGEX "${arg_REGEX}")
        __set_target_link_libraries(${__library} "${__target_libraries}")
    endforeach()
endfunction()
