name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ${{ github.workspace }}/cget
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-cget-${{ hashFiles('requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cget
        cget install pfultz2/rocm-recipes
        cget ignore ROCmSoftwarePlatform/rocBLAS ROCmSoftwarePlatform/MIOpen
        cget install -f requirements.txt
    - name: Build and test
      run: |
        periodic() {
            while :; do
                    echo periodic
                    date
                    sleep 3
                done
        }
        periodic &
        periodic_pid=$!
        rm dev-requirements.txt
        cget build -T check
        kill $periodic_pid
