on:
  workflow_dispatch:
    
name: MiGraphX Benchmark

jobs:
  check_image_version:
    name: Check Image Version
    runs-on: self-hosted
    needs: check_gpu_name
    outputs:
      image: ${{ steps.check_image.outputs.image }}
    steps:
      - name: Check new image
        id: check_image
        run: |
          if [ ! -z "$(docker images -q migraphx-ort:`date +%Y%m%d`)" ]; then
            echo "::set-output name=image::true"
          fi
  build_image:
    name: Build New Image
    runs-on: self-hosted
    needs: check_image_version
    if: ${{ needs.check_image_version.outputs.image == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUB_TOKEN }}
      - name: Docker build
        run: |
          cd ./rocm-migraphx/dockerfiles
          docker build -t "migraphx-ort:$(date +%Y%m%d)" --no-cache -f dockerfile_migraphx_benchmark .
  run_benchmark:
    name: Run benchmark
    runs-on: self-hosted
    if: ${{ always() }}
    needs: build_image
    steps:
      - name: Execute benchmark script
        run: >
          docker run -e TZ=America/Chicago
          -e TARGET=gpu
          --device=/dev/dri
          --device=/dev/kfd
          --network=host
          --group-add=video 
          -v /home/htec/jz:/data
          --workdir /data/source/rocm-migraphx/scripts/
          migraphx-ort:$(date +%Y%m%d) /bin/bash ort_benchmark4.sh