on:
  push:
    branches: [develop]

name: MIOPEN Generate database

env:
  ROCM_VERSION: rocm51
  MIOPEN_PATH: miopen-databases
  
jobs:
  checkout_miopen:
    runs-on: self-hosted
    steps:
      - name: Clone & Push database to git
        run: |
          git clone https://${{ secrets.GH_SUB_TOKEN }}@github.com/migraphx-benchmark/miopen-databases.git ${{ env.MIOPEN_PATH }}
  check_image_version:
    name: Check Image Version
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.check_image.outputs.image }}
    steps:
      - name: Check new image
        id: check_image
        run: |
          if [[ "$(docker image inspect rocm-migraphx:5.1 2> /dev/null)" != "" ]]; then
            echo "::set-output name=image::true"
          fi
      - name: test step
        run: echo "Value of image is ${{ steps.check_image.outputs.image }}"
  check_database:
    name: Check database path
    runs-on: ubuntu-latest
    outputs:
      database: ${{ steps.check_database.outputs.database }}
    steps:
      - name: Check db
        id: check_database
        run: |
          if [ ! -d "${{ env.MIOPEN_PATH }}/${{ env.ROCM_VERSION }}" ]; then
            echo "::set-output name=database::true"
          fi
      - name: test step
        run: echo "Value of database is ${{ steps.check_database.outputs.database }}"
  create_database:
    name: Create MIOpen Database
    runs-on: self-hosted
    needs: [check_image_version, check_database]
    if: ${{ needs.check_image.outputs.image == 'true' }} && ${{needs.check_database.outputs.database == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUB_TOKEN }}
      - name: Perform tuning database
        env:
          MIOPEN_FIND_ENFORCE: 3
        run: >
          docker run -e TZ=America/Chicago
          -e TARGET=gpu
          --device=/dev/dri
          --device=/dev/kfd
          --network=host
          --group-add=video 
          -v /home/htec/jz:/data
          --workdir /data/source/rocm-migraphx/scripts/
          rocm-migraphx:5.1 /bin/bash -c "./run_perf_mev.sh; cp -r /root/.config/miopen /data/database"

      - name: Clone & Push database to git
        run: |
          cd ${{ env.MIOPEN_PATH }}
          mkdir -p ${{env.ROCM_VERSION}}
          cp -r /home/htec/jz/database ${{env.ROCM_VERSION}}
          git add .
          git config --local user.email github-actions
          git config --local user.name github-actions@github.com
          git commit -m "Push databases" -a
          git push



        