name: MIOPEN Generate database

on:
  workflow_dispatch:
    inputs:
      rocm_release:
        description: ROCm release version
        required: true
        default: "5.1"
      miopen_db_repo:
        description: MIOpen Database repository
        default: "migraphx-benchmark/miopen-databases"
        required: true
      script_repo:
        description: Script repository (rocm-migraphx)
        default: "migraphx-benchmark/rocm-migraphx"
        required: true
      saved_models_path:
        description: Saved Models path
        default: "/home/htec/jz/source/saved-models"
        required: true
      test_results_dir:
        description: Test results path
        default: "/home/htec/jz/source/rocm-migraphx/test-results"
        required: true

env:
  ROCM_VERSION: rocm-${{ github.event.inputs.release }}
  MIOPEN_PATH: miopen-databases
  SCRIPT_PATH: rocm-migraphx
  
jobs:
  miopen:
    uses: migraphx-benchmark/actions/.github/workflows/miopen-db.yml@main
    with:
      rocm_release: ${{ inputs.rocm_release }}
      miopen_db_repo: ${{ inputs.miopen_db_repo }}
      script_repo: ${{ inputs.script_repo }}
      saved_models_path: ${{ inputs.saved_models_path }}
      test_results_dir: ${{ inputs.test_results_dir }}
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
          