name: MIGraphX Performance Tests Jovica

on:
#   push:
#     branches: [develop]

#   pull_request:
#     branches: [develop]
#   schedule:
#     - cron: "0 5 * * 1-6"

  workflow_dispatch:
    inputs:
      rocm_release:
        description: ROCm Version
        required: false
      performance_reports_repo:
        description: Result repository
        required: false
      result_number:
        description: Last N results
        required: false
      flags:
        description: -m for Max value; -s for Std dev; -r for Threshold file
        required: false

concurrency: benchmark

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/perf-test.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release || '5.1' }}
      result_number: ${{ github.event.inputs.result_number || '10' }}
      flags: ${{ github.event.inputs.flags || '-s' }} 
      performance_reports_repo: ${{ github.event.inputs.performance_reports_repo || 'migraphx-benchmark/migraphx-reports' }} 
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
