name: MIGraphX Performance Tests

on:
  pull_request_target:
    branches: [develop]
    types: [opened, synchronize, closed, labeled]
  schedule:
    - cron: "0 7 * * 1-6"
  workflow_dispatch:

concurrency: 
  group: "perftest-${{ github.head_ref || github.base_ref || 'schedule' }}"
  cancel-in-progress: true

jobs:
  publish_perf_data:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'schedule' ||
      github.event_name == 'workflow_dispatch' ||
      github.event.action == 'closed' ||
      contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract performance data
        run: |
          mkdir -p test-results
          unzip test/actions/perf_develop/performance-run-data.zip -d test-results

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-run-data
          path: test-results/
