name: MIGraphX Performance Tests

on:
  push:
    branches: [develop]

  pull_request:
    branches: [develop]
  schedule:
    - cron: "0 5 * * 1-6"

  workflow_dispatch:
    inputs:
      rocm_release:
        description: ROCm Version
        required: true
        default: "5.1"
      result_number:
        description: Last N results
        required: true
        default: 10
      flags:
        description: -m for Max value; -s for Std dev; -r for Threshold file
        required: true
        default: "-s"

concurrency: benchmark

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/perf-test.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release }}
      result_number: ${{ github.event.inputs.result_number }}
      flags: ${{ github.event.inputs.flags }} 
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}