on:
  push:
    branches: [develop]

name: RCOM release

jobs: 
  build_image:
    name: Build New Image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
        with:
          remote: true
      - name: Docker build
        run: |
          cd ./rocm-migraphx/scripts
          env ROCM_RELEASE=“5.1” ./build_migraphx_docker.sh