on:
  push:
    branches: [develop]

name: RCOM release

jobs: 
  build_image:
    name: Build New Image
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUB_TOKEN }}
      - name: Docker build
        run: |
          cd ./rocm-migraphx/scripts
          env ROCM_RELEASE=5.1 ./build_migraphx_docker.sh
      # - name: Run Docker script
      #   run: |
      #     docker run -it -e TZ=America/Chicago -e TARGET=gpu --device=/dev/dri --device=/dev/kfd --network=host --group-add=video rocm-migraphx:5.1 /bin/bash