name: MIGraphX Performance Tests

on:
  push:
    branches: [develop]

  pull_request:
    branches: [develop]
  schedule:
    - cron: "0 5 * * 1-6"

  workflow_dispatch:

concurrency: benchmark

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/perf-test.yml@main
    with:
      rocm_release: "5.1"
      result_number: 10
      flags: "-s" 
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}