on:
  workflow_dispatch:
    inputs:
      release:
        description: ROCm release version
        required: true
      git-ref:
        description: Git Ref (Mandatory)
        required: false

name: ROCM release

jobs:
  check_image_version:
    name: Check Image Version
    runs-on: self-hosted
    outputs:
      image: ${{ steps.check_image.outputs.image }}
    steps:
      - name: Check new image
        id: check_image
        run: |
          if [[ "$(docker image inspect rocm-migraphx:${{ github.event.inputs.release }} 2> /dev/null )" == "" ]]; then
            echo "::set-output name=image::true"
          fi
  build_image:
    name: Build New Image
    runs-on: self-hosted
    needs: check_image_version
    if: ${{ needs.check_image.outputs.image == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUB_TOKEN }}
      - name: Docker build
        env:
          ROCM_RELEASE: 5.1
          ROCM_BASE: rocm/dev-ubuntu-18.04:$ROCM_RELEASE
          BUILD_NAVI: "0"
          DOCKERIMAGE: rocm-migraphx:$ROCM_RELEASE
          DOCKERFILE: dockerfile.`date '+%Y-%m-%d'`
        run: |
          sed -e "s?ROCM_RELEASE?$ROCM_RELEASE?g" dockerfile > $DOCKERFILE
          docker build --build-arg build_navi=$BUILD_NAVI --build-arg base_image=$ROCM_BASE --no-cache -t $DOCKERIMAGE -f $DOCKERFILE .
          # env ROCM_RELEASE=5.1 ./build_migraphx_docker.sh
