on:
  workflow_dispatch:
    inputs:
      release:
        description: ROCm release version
        required: true


name: ROCM Docker image build

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/.yml@main
    with:
      release: ${{ inputs.release }}
    secrets:
      gh_token: ${{ secrets.GH_SUB_TOKEN }}
