name: ROCM Docker image build

on:
  workflow_dispatch:
    # inputs:
    #   rocm_release:
    #     description: ROCm release version
    #     required: true

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/rocm-release.yml@main
    with:
      rocm_release: 5.1
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
