name: ROCM Docker image build

on:
  workflow_dispatch:
    inputs:
      release:
        description: ROCm release version
        required: true

jobs:
  release:
    uses: migraphx-benchmark/actions/.github/workflows/rocm-release.yml@main
    with:
      release: ${{ inputs.release }}
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
