on:
  workflow_dispatch:
    inputs:
      release:
        description: ROCm release version
        required: true
      git-ref:
        description: Git Ref
        required: false

name: ROCM release

jobs:
  check_image_version:
    name: Check Image Version
    runs-on: self-hosted
    outputs:
      image: ${{ steps.check_image.outputs.image }}
    steps:
      - name: Check new image
        id: check_image
        run: |
          if [ -z "$(docker images -q rocm-migraphx:${{ github.event.inputs.release }})" ]; then
            echo "::set-output name=image::true"
          fi
      - name: test step
        run: echo "Value of image is ${{ steps.check_image.outputs.image }}"
  build_image:
    name: Build New Image
    runs-on: self-hosted
    needs: check_image_version
    if: ${{ needs.check_image_version.outputs.image == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          submodules: recursive
          token: ${{ secrets.GH_SUB_TOKEN }}
      - name: Docker build
        env:
          ROCM_RELEASE: ${{ github.event.inputs.release }}
          ROCM_BASE: rocm/dev-ubuntu-18.04:${{ github.event.inputs.release }}
          BUILD_NAVI: "0"
          DOCKERIMAGE: rocm-migraphx:${{ github.event.inputs.release }}
        run: |
          cd $GITHUB_WORKSPACE/rocm-migraphx/scripts
          ./build_migraphx_docker.sh
