name: tidy

on: push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build the Docker image
      run: docker build . --file hip-clang.docker --tag migraphx

    - name: Clang tidy
      shell: bash -c "docker run -i -v=$GITHUB_WORKSPACE:/data -w /data migraphx bash < {0}"
      run: |
        env
        mkdir build
        cd build
        CXX=/opt/rocm/llvm/bin/clang++ CC=/opt/rocm/llvm/bin/clang cmake -DCLANG_TIDY_DEPEND_ON_TARGET=Off ..
        cd /data/src/onnx && /opt/rocm/llvm/bin/clang-tidy -config= -p /data/build -checks=boost-*,bugprone-*,cert-*,clang-analyzer-*,clang-diagnostic-*,cppcoreguidelines-*,google-*,hicpp-multiway-paths-covered,hicpp-signed-bitwise,llvm-namespace-comment,misc-*,modernize-*,performance-*,readability-*,-bugprone-signed-char-misuse,-cert-dcl37-c,-cert-dcl51-cpp,-clang-analyzer-alpha*,clang-analyzer-alpha.core.CallAndMessageUnInitRefArg,clang-analyzer-alpha.core.Conversion,clang-analyzer-alpha.core.IdenticalExpr,clang-analyzer-alpha.core.PointerArithm,clang-analyzer-alpha.core.PointerSub,clang-analyzer-alpha.core.TestAfterDivZero,clang-analyzer-alpha.cplusplus.InvalidIterator,clang-analyzer-alpha.cplusplus.IteratorRange,clang-analyzer-alpha.cplusplus.MismatchedIterator,clang-analyzer-alpha.cplusplus.MisusedMovedObject,-clang-analyzer-optin.performance.Padding,-clang-diagnostic-deprecated-declarations,-clang-diagnostic-extern-c-compat,-clang-diagnostic-disabled-macro-expansion,-clang-diagnostic-unused-command-line-argument,-cppcoreguidelines-explicit-virtual-functions,-cppcoreguidelines-init-variables,-cppcoreguidelines-pro-bounds-array-to-pointer-decay,-cppcoreguidelines-pro-bounds-constant-array-index,-cppcoreguidelines-pro-bounds-pointer-arithmetic,-cppcoreguidelines-pro-type-member-init,-cppcoreguidelines-pro-type-reinterpret-cast,-cppcoreguidelines-pro-type-union-access,-cppcoreguidelines-pro-type-vararg,-cppcoreguidelines-special-member-functions,-google-readability-*,-google-runtime-int,-google-runtime-references,-misc-macro-parentheses,-misc-no-recursion,-modernize-concat-nested-namespaces,-modernize-pass-by-value,-modernize-use-default-member-init,-modernize-use-nodiscard,-modernize-use-override,-modernize-use-trailing-return-type,-modernize-use-transparent-functors,-performance-type-promotion-in-math-fn,-readability-braces-around-statements,-readability-convert-member-functions-to-static,-readability-else-after-return,-readability-named-parameter,-readability-redundant-string-init,-readability-uppercase-literal-suffix,-*-avoid-c-arrays,-*-explicit-constructor,-*-magic-numbers,-*-non-private-member-variables-in-classes,-*-use-auto,-*-use-emplace,-*-use-equals-default -warnings-as-errors=*,-readability-inconsistent-declaration-parameter-name -extra-arg=-UNDEBUG -extra-arg=-DMIGRAPHX_USE_CLANG_TIDY -extra-arg=-Dmain\(...\)=main\(__VA_ARGS__\)\ //\ NOLINT -extra-arg=-Xclang -extra-arg=-analyzer-max-loop -extra-arg=-Xclang -extra-arg=10 -extra-arg=-Xclang -extra-arg=-analyzer-inline-max-stack-depth -extra-arg=-Xclang -extra-arg=10 -extra-arg=-Xclang -extra-arg=-analyzer-config -extra-arg=-Xclang -extra-arg=optin.cplusplus.UninitializedObject:Pedantic=true -extra-arg=-Xclang -extra-arg=-analyzer-config -extra-arg=-Xclang -extra-arg=widen-loops=true -extra-arg=-Xclang -extra-arg=-analyzer-config -extra-arg=-Xclang -extra-arg=unroll-loops=true -extra-arg=-Xclang -extra-arg=-analyzer-config -extra-arg=-Xclang -extra-arg=cfg-lifetime=true -extra-arg=-Xclang -extra-arg=-analyzer-config -extra-arg=-Xclang -extra-arg=cfg-scopes=true -header-filter=.*hpp onnx.cpp -export-fixes=/data/build/fixits/migraphx_onnx-onnx_cpp.yaml
        



