name: tidy

on: push

jobs:
  build-container:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    # In this step, this action saves a list of existing images,
    # the cache is created without them in the post run.
    # It also restores the cache if it exists.
    - uses: satackey/action-docker-layer-caching@v0.0.8
      # Ignore the failure of a step and avoid terminating the job.
      continue-on-error: true

    - name: Build the Docker image
      run: docker build . --file hip-clang.docker --tag migraphx

  build-analyze:
    needs: build-container
    runs-on: ubuntu-18.04
    container: migraphx
    - name: Clang tidy
      run: |
        mkdir build
        cd build
        cmake ..
        make analyze


